### ISSUE TITLE
[Question]: How to pass Peach pits into container?

### ISSUE THREAD

**Issue by fockboi-lgtm** [vanhauser-thc/peachpro#2]
Hi,
Thank you for creating this Dockerfile.
But I was not able to get pits into the docker container, how is the recommended way of doing this?

**Comment by vanhauser-thc** [comment]
store them to a directory
docker ... -v /that/directory:/pits ...
and then the pit file is in /pits in the container

**Comment by fockboi-lgtm** [comment]
Thanks
